name: phu_tho_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # Configuration
  flutter_dotenv: ^5.1.0
  package_info_plus: ^5.0.1
  collection: ^1.18.0

  # Localization
  easy_localization: ^3.0.0

  # State management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_value_notifier: ^1.5.1


  # DI
  get_it: ^7.2.0
  injectable: ^2.1.0

  # Local database
  shared_preferences: ^2.2.2

  # Networking
  retrofit: ^4.0.3
  dio: ^5.3.4
  pretty_dio_logger: ^1.3.1
  json_annotation: ^4.4.0
  json_serializable: ^6.1.1
  either_dart: ^1.0.0

  # UI
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^2.0.9
  google_fonts: 6.1.0
  skeletons: ^0.0.3
  flutter_spinkit: ^5.2.0
  pull_to_refresh: ^2.0.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  timelines: ^0.1.0
  animated_bottom_navigation_bar: ^1.3.3
  flutter_slidable: ^3.1.1


  #image
  cached_network_image: ^3.3.1
  animated_read_more_text: 0.0.6
  url_launcher: ^6.3.0
  intl: ^0.18.1
  flutter_html: ^3.0.0-beta.2

  jwt_decoder: ^2.0.1


  #file
  path_provider: ^2.1.3
  open_file: ^3.3.2
  http: ^1.2.0
  webview_flutter: ^4.5.0
  qr_code_scanner:
    git:
      url: https://github.com/dola99/qr_code_scanner
      ref: update
  image: ^4.2.0
  image_picker: ^1.0.8
  webview_flutter_android: ^3.16.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  injectable_generator: ^2.1.4
  retrofit_generator: ^8.0.4
  flutter_gen_runner: ^5.3.2
  husky: ^0.1.7
  lint_staged: ^0.5.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/
    - env/.env.dev
    - env/.env.prod

flutter_gen:
  integrations:
    flutter_svg: true

lint_staged:
  'lib/**.dart': dart format -l 120 && dart analyze --fatal-infos --fatal-warnings
